// File automatically generated by fshasher

#include <utility>

extern const uint64_t EpisodeSilverHashes[];
extern const std::pair<const char *, uint32_t> EpisodeSilverFiles[];
extern const size_t EpisodeSilverFilesSize;

const uint64_t EpisodeSilverHashes[] = {
    12996835580564401141ULL,
};

const std::pair<const char *, uint32_t> EpisodeSilverFiles[] = {
    { "download.arc", 1 },
};

const size_t EpisodeSilverFilesSize = std::size(EpisodeSilverFiles);
