// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t EpisodeSonicHashes[];
extern const std::pair<const char *, uint32_t> EpisodeSonicFiles[];
extern const size_t EpisodeSonicFilesSize;

