// File automatically generated by fshasher

#include <utility>

extern const uint64_t EpisodeSonicHashes[];
extern const std::pair<const char *, uint32_t> EpisodeSonicFiles[];
extern const size_t EpisodeSonicFilesSize;

const uint64_t EpisodeSonicHashes[] = {
    15073381587123252911ULL,
};

const std::pair<const char *, uint32_t> EpisodeSonicFiles[] = {
    { "download.arc", 1 },
};

const size_t EpisodeSonicFilesSize = std::size(EpisodeSonicFiles);
