// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t EpisodeSilverHashes[];
extern const std::pair<const char *, uint32_t> EpisodeSilverFiles[];
extern const size_t EpisodeSilverFilesSize;

