// File automatically generated by fshasher

#include <utility>

extern const uint64_t EpisodeShadowHashes[];
extern const std::pair<const char *, uint32_t> EpisodeShadowFiles[];
extern const size_t EpisodeShadowFilesSize;

const uint64_t EpisodeShadowHashes[] = {
    10539656742164611611ULL,
};

const std::pair<const char *, uint32_t> EpisodeShadowFiles[] = {
    { "download.arc", 1 },
};

const size_t EpisodeShadowFilesSize = std::size(EpisodeShadowFiles);
