// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t EpisodeAmigoHashes[];
extern const std::pair<const char *, uint32_t> EpisodeAmigoFiles[];
extern const size_t EpisodeAmigoFilesSize;

