// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t EpisodeShadowHashes[];
extern const std::pair<const char *, uint32_t> EpisodeShadowFiles[];
extern const size_t EpisodeShadowFilesSize;

