// File automatically generated by fshasher

#include <utility>

extern const uint64_t EpisodeAmigoHashes[];
extern const std::pair<const char *, uint32_t> EpisodeAmigoFiles[];
extern const size_t EpisodeAmigoFilesSize;

const uint64_t EpisodeAmigoHashes[] = {
    8983387072646869383ULL,
};

const std::pair<const char *, uint32_t> EpisodeAmigoFiles[] = {
    { "download.arc", 1 },
};

const size_t EpisodeAmigoFilesSize = std::size(EpisodeAmigoFiles);
