// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t MissionSonicHashes[];
extern const std::pair<const char *, uint32_t> MissionSonicFiles[];
extern const size_t MissionSonicFilesSize;

