// File automatically generated by fshasher

#include <utility>

extern const uint64_t MissionSonicHashes[];
extern const std::pair<const char *, uint32_t> MissionSonicFiles[];
extern const size_t MissionSonicFilesSize;

const uint64_t MissionSonicHashes[] = {
    11577193563383386051ULL,
};

const std::pair<const char *, uint32_t> MissionSonicFiles[] = {
    { "download.arc", 1 },
};

const size_t MissionSonicFilesSize = std::size(MissionSonicFiles);
