// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t MissionShadowHashes[];
extern const std::pair<const char *, uint32_t> MissionShadowFiles[];
extern const size_t MissionShadowFilesSize;

