// File automatically generated by fshasher

#include <utility>

extern const uint64_t MissionSilverHashes[];
extern const std::pair<const char *, uint32_t> MissionSilverFiles[];
extern const size_t MissionSilverFilesSize;

const uint64_t MissionSilverHashes[] = {
    7936137245680593367ULL,
};

const std::pair<const char *, uint32_t> MissionSilverFiles[] = {
    { "download.arc", 1 },
};

const size_t MissionSilverFilesSize = std::size(MissionSilverFiles);
