// File automatically generated by fshasher

#include <utility>

extern const uint64_t MissionShadowHashes[];
extern const std::pair<const char *, uint32_t> MissionShadowFiles[];
extern const size_t MissionShadowFilesSize;

const uint64_t MissionShadowHashes[] = {
    14477816605833199221ULL,
};

const std::pair<const char *, uint32_t> MissionShadowFiles[] = {
    { "download.arc", 1 },
};

const size_t MissionShadowFilesSize = std::size(MissionShadowFiles);
