// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t MissionSilverHashes[];
extern const std::pair<const char *, uint32_t> MissionSilverFiles[];
extern const size_t MissionSilverFilesSize;

